import { TranslationProvider } from "../contexts/TranslationContext";
import Head from "next/head";
import "@/helpers/translate";
import ChakraProvider from "@/contexts/ChakraProvider";
import "./styles.scss";

export default function App({ Component, pageProps }) {
  return (
    <ChakraProvider>
      <TranslationProvider>
        <Head>
          <title>News</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="referrer" content="no-referrer"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </TranslationProvider>
    </ChakraProvider>
  );
}
